// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQOzM5mMji5mY5MKEYc9tQezVqX202zWc',
    appId: '1:645221568958:web:4e84767dd6efea4b3569ef',
    messagingSenderId: '645221568958',
    projectId: 'invoice-maker-8d7b4',
    authDomain: 'invoice-maker-8d7b4.firebaseapp.com',
    storageBucket: 'invoice-maker-8d7b4.appspot.com',
    measurementId: 'G-151EEF77J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUu2PvgTXDECXtVBT9e15S5MCCSk1VwO8',
    appId: '1:645221568958:android:5604f918f165b5383569ef',
    messagingSenderId: '645221568958',
    projectId: 'invoice-maker-8d7b4',
    storageBucket: 'invoice-maker-8d7b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDISQCYCRp-mzQ0901e_V7hGJcXr1dqUBE',
    appId: '1:645221568958:ios:6b29ac31e6cd9cc53569ef',
    messagingSenderId: '645221568958',
    projectId: 'invoice-maker-8d7b4',
    storageBucket: 'invoice-maker-8d7b4.appspot.com',
    iosBundleId: 'com.example.invoiceMakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDISQCYCRp-mzQ0901e_V7hGJcXr1dqUBE',
    appId: '1:645221568958:ios:518237cc05fee5113569ef',
    messagingSenderId: '645221568958',
    projectId: 'invoice-maker-8d7b4',
    storageBucket: 'invoice-maker-8d7b4.appspot.com',
    iosBundleId: 'com.example.invoiceMakerApp.RunnerTests',
  );
}
